import type { Metadata } from "next";
//import Header from '../components/layout/Header';
import {Header} from '../components/Header/Header';
import Footer from '../components/layout/Footer';
import "./globals.css";


export const metadata: Metadata = {
  title: "Bonga Digital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />       
        {children}
        <Footer />
      </body>
    </html>
  );
}
